#!/usr/bin/env ansible-playbook

---

- hosts: bludau-1-scaleout1
  remote_user: root
  roles:
    - preconfigure 
    - deployment
    - hsr

- hosts: bludau-1-scaleout2
  remote_user: root
  roles:
    - preconfigure
    - deployment
    - hsr

...
