---

- name: create usr sap directory
  file:
    path: "/usr/sap/{{ sap_system_id|upper }}"
    state: directory

- name: create system sap directory
  file:
    path: "/hana/shared/{{ sap_system_id|upper }}"
    state: directory

- name: create sapsys group
  group: name=sapsys gid={{ id_group_sapsys }}

- name: create sapadm user
  user:
    name: sapadm
    uid: "{{ id_user_sapadm }}"
    group: sapsys
    password: "{{ pw_sapadm|password_hash('sha512') }}"

- name: create sap sid group
  group: name={{ sap_system_id|lower }}shm gid={{ id_group_shm }}

- name: create sap sid user
  user:
    name: "{{ sap_system_id|lower }}adm"
    uid: "{{ id_user_sidadm }}"
    group: "{{ sap_system_id|lower }}shm"
    home: "/usr/sap/{{ sap_system_id|upper }}/home"
    password: "{{ pw_sidadm|password_hash('sha512') }}"

- name: copy installation answer file
  template: src=hana_install.cfg.j2 dest=/tmp/hana_install_{{ sap_system_id|lower}}.cfg

- name: copy global.ini
  copy: src=global.ini dest=/hana/shared/{{ sap_system_id|upper }}/global.ini

  # TODO Install SAPHOSTAGENT

- name: execute unattended installation (logfile /var/log/hana_install.log )
  shell: ./hdblcm --configfile=/tmp/hana_install_{{ sap_system_id|lower}}.cfg -b --remote_execution=saphostagent >> /var/log/hana_install.log
  args:
    chdir: "{{ installroot }}/DATA_UNITS/HDB_SERVER_LINUX_X86_64/"
    creates: "/usr/sap/{{ sap_system_id|upper }}/HDB{{ sap_instance }}/exe/hdbdaemon"

...
