---

- name: Enable Debugging
  debug:
    verbosity: "{{ debuglevel }}"

# Thomas Bludau 20170508
# Changed on every Customer Side
# It is necessary that you have a fix repository, 
# otherwhise added systems could have problems
# Requirement is that the systems are Registed to 
# existing Repository.


- include: ./system-registration-part1.yml
  when: check_repos
  tags:
    - osprep
    - system-registration


- include: "{{ './' + ansible_distribution + ansible_distribution_major_version + '/system-registration.yml' }}"
  when: check_repos
  tags:
    - osprep
    - system-registration

- include: "{{ './' + ansible_distribution + ansible_distribution_major_version + '/package-installation.yml' }}"
  tags:
    - osprep
    - packages
- include: "{{ './' + ansible_distribution + ansible_distribution_major_version + '/service-configuration.yml' }}"
  tags:
    - osprep
    - services
- include: "{{ './' + ansible_distribution + ansible_distribution_major_version + '/system-tuning.yml' }}"
  tags:
    - osprep
    - system-tuning

- include: "{{ './' + ansible_distribution + ansible_distribution_major_version + '/check-hostname-dns.yml' }}"
  tags:
    - osprep
    - set-hostname

- include: ./disk-partitioning.yml
  when: 
    - disk_partitioning
  tags:
    - osprep
    - disk_partitioning

- include: ./sap-check-media.yml
  tags:
    - hana-install
    - media-check

...
