---

disk_partitioning: false

ntpserver: ntp.mcs.hpemea.net

disks:
  /dev/vdc: vg00
  /dev/vdb: vg01

logvols:
  hana_shared:
    size: 24G
    vol: vg00
    mountpoint: /hana/shared
    pvs: /dev/vdc1
  hana_data:
    size: 24G
    vol: vg00
    mountpoint: /hana/data
    pvs: /dev/vdc1
  hana_logs:
    size: 12G
    vol: vg00
    mountpoint: /hana/logs
    pvs: /dev/vdc1
  install:
    size: 128G
    vol: vg00
    mountpoint: /install
    pvs: /dev/vdc1
  usr_sap:
    size: 49G
    vol: vg01
    mountpoint: /usr/sap
    pvs: /dev/vdb1

id_user_sapadm: "30200"
id_user_sidadm: "30210"
id_group_shm: "30220"
id_group_sapsys: "30200"

pw_sapadm: "Adm12356"
pw_sidadm: "Adm12356"
pw_systemuser: "System123"

installroot: /install
installversion: 51051151

installdir: "{{ installroot }}/{{ installversion }}"

sap_system_id: "HMC"
sap_instance: "01"
sap_hostname: "{{ ansible_hostname }}"
sap_hana_system_usage: "custom"
sap_hana_components: "client,server"
sap_hana_system_type: "Master"
sap_hana_autoinstall: false

...
