---

- file:
    name: "{{  installroot }}"
    state: directory
    owner: root
    group: root


- name: Make Installdir available at '{{ installroot }}'
  shell: |
    INSTDIR='{{ installroot }}'
    VERSION='{{ installversion }}'
    MOUNTP='{{ install_nfs }}'
    if [ -f "${INSTDIR}/DATA_UNITS/HDB_SERVER_LINUX_X86_64/hdblcm" ]; then
       rc=0
    else
       TDIR=$(mktemp -d)
       trap "{ cd / ; rm -rf $TDIR; exit 255; }" SIGINT
       mount -t nfs $MOUNTP $TDIR
       if [ -d "${TDIR}/${VERSION}" ]; then 
          umount "$TDIR"
          mount -t nfs $MOUNTP $INSTDIR
          rc=1
       else
          if [ -f "${TDIR}/${VERSION}_part1.exe" ]; then 
             ( cd $INSTDIR; unrar x "${TDIR}/${VERSION}_part1.exe" )
             umount ${TDIR}
             rc=1
          else
             rc=2
          fi
       fi 
    fi
    rm -rf $TDIR
    exit $rc
  register: unpack_hana 
  changed_when: unpack_hana.rc == 1
  failed_when: unpack_hana.rc >= 2 
  when: not( (install_nfs is undefined) or (install_nfs is none) or (install_nfs | trim == '') )

# Changed Thomas Bludau (20170508)
# Install directory could named completly different by customer
# Use only installroot for installation
# Otherwise you got problems while integrating on customers side ...

- name: Get HANA Version Information
  shell: |
    INSTDIR='{{ installroot }}'
    awk ' ( $1 == "fullversion:" ) { print $2}'  ${INSTDIR}/DATA_UNITS/HDB_SERVER_LINUX_X86_64/server/manifest
  register: hanaversion

...
