---
# Global Default variables
# Adapt to your default settings

# Want extensive debugging
debuglevel: 3
#
#  System Registration. 
# assuming system is properly configured, just want to add required channels
force_repo_reset: false
check_repos: true

# Disk Setup
# disk setup is done by kickstart, so no need to change anything here
disk_partitioning: false

ntpserver: pool.ntp.org

disks:
  /dev/vdc: vg00
  /dev/vdb: vg01

logvols:
  hana_shared:
    size: 24G
    vol: vg00
    mountpoint: /hana/shared
    pvs: /dev/vdc1
  hana_data:
    size: 24G
    vol: vg00
    mountpoint: /hana/data
    pvs: /dev/vdc1
  hana_logs:
    size: 12G
    vol: vg00
    mountpoint: /hana/logs
    pvs: /dev/vdc1
  install:
    size: 128G
    vol: vg00
    mountpoint: /install
    pvs: /dev/vdc1
  usr_sap:
    size: 49G
    vol: vg01
    mountpoint: /usr/sap
    pvs: /dev/vdb1

# HANA Parameters
#hsr_name: demoinstall

# directory, where Hana install binaries are unpacked
#hana_installdir: /install
#installversion: "51051151"

# User and GroupIDs to use for sap (Default: undef)
#id_user_sapadm: "30200"
#id_user_sidadm: "30210"
#id_group_shm: "30220"
#id_group_sapsys: "30200"
#pw_user_sapadm_clear: "Adm12356"
#pw_user_sidadm: "Adm12356"
#hana_pw_system_user_clear: "System123"
#
#hana_sid: HXE
#hana_instance_number: 90
#
#hana_system_usage: custom
#
hana_components: "client,server"
#
hana_system_type: "Master"

...
    
