---
# Global Default variables
# Adapt to your default settings

# Want extensive debugging
debuglevel: 3
#
#  System Registration.
# assuming system is properly configured, just want to add required channels
force_repo_reset: false
check_repos: true

rhel_7_repos:
  - rhel-7-server-eus-rpms
  - rhel-sap-hana-for-rhel-7-server-eus-rpms

rhel_6_repos:
  - rhel-6-server-eus-rpms
  - rhel-sap-hana-for-rhel-6-server-eus-rpms
  - rhel-sfs-for-rhel-6-server-eus-rpms
  
# Disk Setup
# disk setup is done by kickstart, so no need to change anything here
disk_partitioning: false

ntpserver: pool.ntp.org

disks:
  /dev/vdc: vg00
  /dev/vdb: vg01

logvols:
  hana_shared:
    size: 24G
    vol: vg00
    mountpoint: /hana/shared
    pvs: /dev/vdc1
  hana_data:
    size: 24G
    vol: vg00
    mountpoint: /hana/data
    pvs: /dev/vdc1
  hana_logs:
    size: 12G
    vol: vg00
    mountpoint: /hana/logs
    pvs: /dev/vdc1
  install:
    size: 128G
    vol: vg00
    mountpoint: /install
    pvs: /dev/vdc1
  usr_sap:
    size: 49G
    vol: vg01
    mountpoint: /usr/sap
    pvs: /dev/vdb1

...
